on: [push, pull_request]

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} R ${{ matrix.r-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, macos-14, ubuntu-24.04, windows-2022 ]
        r-version: [ release, devel ]

    steps:
      - uses: actions/checkout@v4
        
      - name: Install R
        uses: s-u/R-actions/install@master
        with:
          r-version: ${{ matrix.r-version }}
          tools: base

      - uses: s-u/R-actions/tinytex@master

      - uses: s-u/R-actions/pkg-check@master
        with:
          check-flags: --as-cran
          debian-deps: libcurl4-openssl-dev
  
